// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============== WEB (金鑰已根據您的截圖自動填入) ==============
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC0ASuanMIWPyYo4wALc52k9pUbJp9R-qE",
    appId: "1:827247802510:web:fid0fbce476c0fa97871df",
    messagingSenderId: "827247802510",
    projectId: "dingding-tarot-77424",
    authDomain: "dingding-tarot-77424.firebaseapp.com",
    storageBucket: "dingding-tarot-77424.appspot.com",
    measurementId: "G-52W37401XY",
  );

  // ============== ANDROID (請替換為您的 Android App 金鑰) ==============
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: 'YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: 'YOUR_ANDROID_MESSAGING_SENDER_ID_HERE',
    projectId: 'dingding-tarot-77424',
    storageBucket: 'dingding-tarot-77424.appspot.com',
  );

  // ============== iOS (請替換為您的 iOS App 金鑰) ==============
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: 'YOUR_IOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID_HERE',
    projectId: 'dingding-tarot-77424',
    storageBucket: 'dingding-tarot-77424.appspot.com',
    iosBundleId: 'com.example.damiwu',
  );

  // ============== MACOS (請替換為您的 macOS App 金鑰) ==============
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_MACOS_MESSAGING_SENDER_ID_HERE',
    projectId: 'dingding-tarot-77424',
    storageBucket: 'dingding-tarot-77424.appspot.com',
    iosBundleId: 'com.example.damiwu',
  );
}
